package lux.xquery;

import lux.xml.ValueType;
import lux.xpath.AbstractExpression;

/**
 * This class exists purely as a marker for the optimizer.  It indicates the existence of a type-checking
 * expression generated by Saxon's optimizer (ItemChecker / AtomicSequenceConverter). 
 *
 */
public class AtomizedSequence extends TreatAs {

	public AtomizedSequence(AbstractExpression expr, ValueType valueType, String occurrence) {
		super(expr, valueType, occurrence);
	}

}
